name: 'Run tests on Bun'

on:
  push:
    paths:
    - '.github/workflows/bun.yml'
    - 'tests/**'
    - 'types/**'
    - 'index.ts'
    - 'package.json'
    - 'pnpm-lock.yaml'
  pull_request:
    paths:
    - '.github/workflows/bun.yml'
    - 'tests/**'
    - 'types/**'
    - 'index.ts'
    - 'package.json'
    - 'pnpm-lock.yaml'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 10

    - uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1.2.1

    - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      name: Set up Bun cache
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      run: |
        bun install --frozen-lockfile --strict-peer-dependencies

    - name: Lint Source
      run: bun run --if-present lint

    - name: Build Source
      run: bun run --if-present build

    - name: Run Tests
      run: bun run --if-present test
