name: 'Run tests on Deno'

on:
  push:
    paths:
    - '.github/workflows/deno.yml'
    - 'tests/**'
    - 'types/**'
    - 'index.ts'
    - 'package.json'
    - 'pnpm-lock.yaml'
  pull_request:
    paths:
    - '.github/workflows/deno.yml'
    - 'tests/**'
    - 'types/**'
    - 'index.ts'
    - 'package.json'
    - 'pnpm-lock.yaml'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 10

    - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
      with:
        deno-version: v1.x

    - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
      name: Set up Deno cache
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Lint Source
      run: deno lint --rules-exclude=no-explicit-any --ignore=node_modules **/*.ts

    - name: Run Tests
      run: deno run --allow-all --unstable-sloppy-imports npm:uvu tests
