name: "Run tests on Deno"

on:
  push:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/cache@v4
        name: Set up Deno cache
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install uvu
        run: |
          deno cache npm:uvu \
          --allow-scripts \
          --node-modules-dir=auto

      - name: Lint Source
        run: deno run --allow-all npm:@biomejs/biome ci

      - name: Run Tests
        run: deno run --allow-all --unstable-sloppy-imports npm:uvu tests
